import _ from 'lodash';

let words = {
    colors: {
        Black: 'Kappu',
        Blue: 'Neeli',
        Colors: 'BannagaLu',
        Green: 'Hasiru',
        Orange: 'KittaLe',
        Pink: 'Gulabi',
        Purple: 'Gadugempu (not usually used)',
        Red: 'Kempu',
        White: 'Bili',
        Yellow: 'Haladi',
    },
    regular: {
        'Able': 'Saadhya',
        'Above': 'Mele',
        'Absent': 'Gairu',
        'Accept': 'Sweekarisu',
        'Accident': 'Apagaatha (but people use accident only)',
        'Address': 'Vilasa',
        'After <something>': 'Idda mele',
        'After': 'Mattay',
        'Again': 'Innondusala',
        'Against (not accepting)': 'Nirakarisu',
        'Age': 'Vayassu',
        'Agree': 'Oppu',
        'ASAP': 'Aadashtu Bega',
        'Air': 'Gaali',
        'Airport': 'Vimana Nildana',
        'And': 'Mattu',
        'Answer': 'Uttara',
        'Application': 'Arji',
        'Ask/Hear/Listen': 'KeLi',
        'Asleep': 'Nidre',
        'Awake': 'Ecchara',
        'Baby': 'Magu',
        'Bad': 'KeTta',
        'Bath': 'Snana',
        'Behaviour': 'Nadavalike',
        'Behind/Back': 'Hinde',
        'Beka': 'Do you want',
        'Bell': 'Ghante',
        'Below': 'Kelage',
        'Best': 'Uttama',
        'Big': 'Dodda',
        'Birth': 'Huttu',
        'Bitter': 'Kahi',
        'Boat': 'Doni',
        'Book': 'Pustaka',
        'Boy': 'Huduga',
        'Bring': 'Thanni',
        'But': 'Aadre',
        'Calling someone (with respect like Boss)': 'Guru',
        'Certainly': 'Kanditavaagi',
        'Chair': 'Kurchi',
        'Children (with love)': 'Makkale',
        'Children': 'Makkalige',
        'City': 'Ooru',
        'City': 'Pattana ',
        'Close to someone': 'Maga',
        'Close': 'Haaki',
        'Cloud': 'Moda',
        'Cold Weather': 'ChaLLi',
        'Cold': 'ThaNNage',
        'Come': 'Banni',
        'Coming': 'Bartini',
        'Common insult': 'Nimmajji (grandmother insult)',
        'Community': 'Jaathi',
        'Complete or finish': 'Mugisi',
        'Complete': 'Hogisu (don’t say) or Mogisu ',
        'Congratulations': 'ShubhashayagaLu',
        'Cook (process)': 'Adige',
        'Country': 'Desha',
        'Cry': 'ALu',
        'Daalo/Put': 'Haaki',
        'Dance': 'Nrutya',
        'Date': 'Taariku / Dinanka ',
        'Daughter in law': 'Sose',
        'Daughter': 'MagaLu',
        'Day after tomorrow': 'NaaLeDu',
        'Day before yesterday': 'Monne',
        'Day': 'Dina',
        'Death': 'Saavu',
        'Didnt Like': 'Ishtailla',
        'Disagree': 'Oppuvudilla',
        'Do': 'Maadi / Maadu (one word sentence)',
        'Doing': 'Maadutini',
        "Don't tell (singular)": 'HeLaBeda',
        'Donkey': "Katte (you don't understand kannada katte)",
        "Don't tell (plural or with respect)": 'HeLabedi',
        'Door': 'Baagilu',
        'Drink': 'Kudi',
        'Early': 'Bega',
        'Ears': 'Kivi',
        'Earth': 'Bhoomi',
        'Education': 'Vidhyabhyas',
        'Elder Sister': 'Akka',
        'Empty': 'Khali',
        'Enjoy': 'Maja',
        'Everyone': 'YeLLaru',
        'Everyone': 'Yellaru',
        'Excuse Me': 'Illi NoDu',
        'Extremely happy or good': 'Sakkat (Sakkatigide)',
        'Eyes': 'KaNNu',
        'Face': 'Mukha',
        'Far': 'Para',
        'Fast': 'Bega',
        'Father': 'Tande',
        'Fever': 'Jwara',
        'Few': 'Swalpa',
        'Fighting with someone, say get lose': 'Hogolo, with girls Hogele',
        'Finish': 'Kone (Anthya)',
        'First': 'ModaLu',
        'Flower': 'Hoovu',
        'For/To': 'Ge',
        'Forest': 'Kaadu',
        'Fortnight': 'Eradu Varakomme',
        'Front': 'Munde (or mumbe)',
        'Full': 'Poorna',
        'Gents': 'Gandasarige',
        'Get Up': 'EddeL beku',
        'Get': 'Tartini',
        'Girl': 'Hudugi',
        'Give': 'Kodi / Kodu (one word sentence)',
        'Give': 'Kodu',
        'Go': 'Hoogi',
        'God': 'Devaru',
        'Going': 'Hodtini / Hogutide',
        'Good': 'Olleya',
        'Grandfather': 'Tatta',
        'Grandson': 'Mommaga',
        'Hands': 'KaigaLu',
        'Happy': 'Khushi',
        'Hard (strong, not difficult)': 'Gatti',
        'Have': 'Ide',
        'Healthy': 'Arogyakara',
        'Hear': 'KeLu (OWS) KeLi otherwise',
        'Hear/Listen/Ask': 'KeLi',
        'Hello': 'Hello',
        'Help': 'Sahaya',
        'Here': 'illi',
        'Hire': 'Baadige',
        'Holiday': 'Raja',
        'Hot': 'Bisi',
        'House': 'Mane',
        'How': 'Hege',
        'Hunger/Hungry': 'Hasivu',
        'Husband': 'GenDa',
        'If someone is doing fraud': 'Chatri',
        'Important': 'Mukhya',
        'Inform': 'Tilisu',
        'Inside': 'Olage',
        'Introduction': 'Parichaya',
        'Invisible': 'Agochara',
        'Is': 'Aagide',
        "It's there": 'Ide',
        'Join': 'JoDi',
        'Joke': 'Thamashe',
        'Keep': 'Yitko (one word sentence)',
        'Key': 'Kai',
        'Kiss': 'Mutu',
        'Knife': 'Chaaku',
        'Know': 'Gothu',
        'Ladies': 'Hengasarige',
        'Land': 'Zameenu',
        'Language': 'Bhaashe',
        'Last': 'Kone',
        'Later': 'Nantara',
        'Laugh': 'Nagu',
        'Learn': 'Kali',
        'Leave (Holiday)': 'Raje',
        'Legs': 'KaaLugaLu',
        'Less': 'Kadime',
        'Lies': 'SuLu',
        'Lightning': 'Minchu',
        'Like': 'Ishta',
        'Lips': 'TutigaLu',
        'Listen/Here/Ask': 'KeLi',
        'Live': 'Vasisuttidene',
        'Lock': 'Meega',
        'Love': 'Preethi',
        'Many': 'Thumba',
        'Many/More': 'Tumba',
        'Market': 'Marukatte',
        'Marriage': 'Maduve',
        'Meet': 'Beti',
        'Memory': 'Nenapu',
        'Minute': 'Nimsha',
        'Money': 'Duddu',
        'Month': 'Tingalu',
        'Moon': 'Chandra',
        'More than good or more happy': 'Chindi',
        'More': 'Jasti',
        'Morning': 'BeLige',
        'Mother in law': 'AAtte',
        'Mother': 'Taayi',
        'Mouth': 'Baayi',
        'New': 'Hosa',
        'Next Week': 'Mundina Vaara',
        'No Problem': 'Paravagilla',
        'No': 'illa',
        'Noisy': 'Gaddala',
        'Nose': 'Mugu /Moogu',
        'Not come': 'Barala or baralilla',
        'Not go': 'Hogalla',
        'Not there': 'Illa',
        'Now': 'Eega/Evaga',
        'Numbers': 'SankyegaLu',
        'Old': 'Haleya',
        'Older brother': 'ANNa',
        'Only': 'Maatra',
        'Open': 'Tegi',
        'Or': 'Athva',
        'Outside': 'Horage / Aache',
        'Over happy, super happy': 'Bombat',
        'Over (completed)': 'Ayta',
        'Owl': 'Goobe (i understand you Goobe)',
        'Pain': 'Novu',
        'Paper': 'Kaagada',
        'Place': 'Stala',
        'Planet': 'GrahagaLu',
        'Poor': 'Badava',
        'Practice': 'Abhyasa',
        'Prayer': 'Prarthane',
        'Present': 'Hajaru',
        'Price': 'Bele',
        'Purchase/Buy': 'Kharidi',
        'Quarrel': 'Jagala',
        'Question': 'Prashne',
        'Question': 'Prashne',
        'Quiet': 'Nishyabda',
        'Rail/Train Station': 'Rail Nildana',
        'Rain': 'MaLe (muh-lay)',
        'Read': 'Hodu',
        'Ready': "Generally use 'readyu' but Taiyaru",
        'Rich': 'Srimanthike',
        'River': 'Nadi',
        'Run': 'Odu',
        'Run': 'oDu',
        'Rupee': 'Rupay',
        'Say': 'HeLu',
        'Sea': 'Samudra',
        'Season': 'Gaala',
        'See': 'Nodu (one word sentence)',
        'See': 'NooDi',
        'Sell': 'Maaru',
        'Sell': 'Marata',
        'Send': 'Kalisu (one word sentence)',
        'Shall I': 'Eega',
        'Shall We': 'agona',
        'Shop': 'Angadi',
        'Short': 'Kulla',
        'Sick': 'Anarogya',
        'Sit Down': 'Kulitiko / KutkoLi (with respect)',
        'Sky': 'Aakasha',
        'Status': 'Stithi',
        'Sleep': 'Malagu',
        'Sleeping': 'Malko beku',
        'Slow': 'Nidhaana',
        'Small': 'Sanna (Chikka)',
        'Snow/Mist': 'Hima',
        'So much': 'Ishtu',
        'Society': 'Samaja',
        'Soft': 'Mrudu',
        'Some': 'KeLavu',
        'Son': 'Maga',
        'Song': 'Haadu',
        'Sorry': 'Tappaytu/Khsamisi',
        'Speak': 'Mathadu (one word sentence)',
        'Speech (like a politician)': 'Bhashana',
        'Speech': 'Maatu',
        'Spoon': 'Chamacha',
        'Stand up': 'Nintuko / Ninkoli',
        'Start': 'Shuru / Prarambha',
        'State': 'Rajya',
        'Stop': 'Nillu',
        'Storm': 'Maaruta',
        'Student': 'Vidhyarthi',
        'Study': 'Odu',
        'Summer': 'Besige',
        'Sun': 'Surya',
        'Sunshine': 'Sooryaprakasha',
        'Sweet': 'Sihi',
        'Table': 'Meju',
        'Take this': 'Tegaduko',
        'Take': 'Thago',
        'Tall': 'Ettara',
        'Tell': 'HeLi',
        'Tenses': 'Kaala',
        'Thank You': 'Dhanyavadagalu',
        'There': 'Alli',
        'Thick': 'Dappa',
        'Thief': 'KaLLa',
        'Thin': 'Badava',
        'Thunder': 'Gudugu',
        'Time': 'Kaala',
        'To/For': 'Ge',
        'Today': 'Ivathu',
        'Together': 'Jottege',
        'Tomorrow': 'NaLe',
        'Tongue': 'Naalige',
        'Town': 'Pattana',
        'Trouble': 'Tondare',
        'Unable': 'Asaadhya',
        'Use when someone tries to fool you and you know better': 'Suryangetorcha/Tirupatigeladdu/Samudrageuppa',
        'Use with scolding': 'Magane',
        'Value': 'Maulya',
        'Vehicle': 'Gaadi',
        'Village': 'Halli',
        'Visible': 'Gochara',
        'Walk': 'NaDi',
        'Wash': 'Toli',
        'Watch (The one that tells time)': 'Gadiyara',
        'We': 'Naavu',
        'Week': 'Vaara',
        'Weight': 'Tooka',
        'Went': 'Hogide',
        'White Pearl': 'Mutu',
        'Wide': 'Agala (window is wide)',
        'Wife': 'Hendati',
        'Wind': 'Galli',
        'Window': 'Kitaki',
        'Winter Season': 'Chaligaala',
        'Wish': 'Shubhashayagalu',
        'Work': 'Kelasa',
        'Worst': 'Ketta',
        'Write': 'Bari',
        'Year': 'Varsha',
        'Yes': 'Howdu',
        'Yesterday': 'Nenne',
        'Younger brothher': 'Tamma',
        'Younger person close to you': 'Shishya',
        'Younger Sister': 'Tangi',
        'Your Welcome': 'Swagatha',
    },
    food: {
        'Breakfast/Tiffen/Snacks': 'Tindi',
        'But': 'Aadre',
        'Butter': 'Benne',
        'Chicken': 'KoLi',
        'Coconut': 'Tengina Kayi',
        'Come': 'Banni',
        'Coming': 'Bartini',
        'Curds': 'Mosaru',
        'Dal': 'Bele',
        'Eat': 'TinDe',
        'Egg': 'Motte',
        'Fish': 'Meenu',
        'Food': 'Ahara',
        'Fruit': 'Hannu',
        'Ghee': 'Tuppa',
        'Ginger': 'Shunti',
        'Grape': 'Drakshi',
        'Green Leaves': 'Soppu',
        'Lunch/Dinner': 'Oota',
        'Milk': 'Haalu',
        'Mutton': 'Mamsa',
        'Onion': 'Iruli',
        'Pickle': 'Uppina Kai',
        'Potato': 'Alugadde',
        'Pour Water': 'Neeru haaki',
        'Rice': 'Anna',
        'Sabji': 'Palya',
        'Salt': 'Uppu',
        'Sambar': 'Saaru',
        'Sprouts': 'Molake',
        'Sugar': 'Sakkare',
        'Vegetable': 'Tarakaari',
        'Water': 'Neeru',
    },
    numbers: {
        'One': 'OOnedu',
        'Two': 'Eradu',
        'Three': 'Mooru',
        'Four': 'Nalku',
        'Five': 'Aydu',
        'Six': 'Aaru',
        'Seven': 'YeLu',
        'Eight': 'Entu',
        'Nine': 'Ombattu',
        'Ten': 'Hattu',
        'Eleven': 'Hann Ondu',
        'Twenty': 'Ipatu',
        'Twenty One': 'Ipatu Ondu',
        'Thirty': 'Muvatu',
        'Thirty Three': 'Muvatu ooru',
        'Fourty': 'Nalavatu',
        'Fourty Four': 'Nalavatu Nalku',
        'Fifty': 'Aivatu',
        'Sixty': 'Aaravatu',
        'Seventy': 'Epatu',
        'Eighty': 'Embatu',
        'Ninety': 'Tombattu',
        'Hundred': 'Nooru',
        'Hundred & One': 'Nooru Onedu',
        'Hundred & Ten': 'Nooru Hattu',
        'Thousand': 'Savira',
        'Lakh': 'Laksha',
        'Crore': 'Koti',
    },
    speech: {
        'Always': 'Yaavaagalu',
        'And': 'Mattu',
        'Bye (to elders)': 'Namaste',
        'Bye (to friends)': 'Hogi bartini',
        'He (near & far)': 'Evanu / Avanu',
        'He/She/They (respect)': 'Evaru',
        'He/She/They': 'Evanu',
        'Here': 'Illi',
        'Hi/Hello': 'Namaskara',
        'His/Her/Their (far)': 'Avara',
        'His/Her/Their (far)': 'Avaradu',
        'Their (near)': 'Evara',
        'Their (far)': 'Evaradu',
        'How': 'Hege',
        'I': 'Naanu or Nanage',
        'Is it not': 'Alvaa',
        'It': 'Adu',
        'Its': 'Ega',
        'Know': 'Gothu',
        'Mine': 'Nandhu',
        'My': 'Nanna',
        'No': 'Illa',
        'Only': 'Maatra',
        'Or': 'Athva',
        'Our': 'Namma',
        'She (near & far)': 'EvaLu / AvaLu',
        'That (in a group)': 'Aadu',
        'That (not in a group)': 'Adu',
        'There': 'Alli',
        'This': 'Idu or EE',
        'To/For': 'Ge',
        'Want': 'Beku',
        'We': 'Naavu',
        'What': 'Yenu',
        'When': 'Yaavaaga',
        'Where': 'Yelli',
        'Which One': 'Yavdu',
        'Which': 'Yaava / Yaavadhu',
        'Who': 'Yaaru',
        'Whose (Group)': 'Yaaradhu',
        'Whose (One person)': 'Yaara',
        'Why': 'Yaake',
        'With': 'Jote',
        'Yes': 'Howdhu',
        'You': 'Neenu / Neevu',
        'Your': 'Ninna / Nimma',
        'Yours': 'Nindhu / Nimdhu',
    },
    all: {},
};

_.keys(words).forEach((category) => {
    words.all = _.extend(words.all, words[category]);
});

export default words;
